// <auto-generated />
using System;
using Assignment.Web.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment.Web.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    [Migration("20190404170823_Mig_MarkupPlanAdedd")]
    partial class Mig_MarkupPlanAdedd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment.Web.Models.BusinessEntities", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Balance");

                    b.Property<string>("City")
                        .HasMaxLength(150);

                    b.Property<string>("Code")
                        .HasMaxLength(50);

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Country")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedOnUtc");

                    b.Property<float>("CurrentBalance");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email");

                    b.Property<string>("LoginUrl")
                        .HasMaxLength(50);

                    b.Property<string>("Logo");

                    b.Property<int>("MarkupPlanId");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50);

                    b.Property<string>("Name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("ReferredBy")
                        .HasMaxLength(50);

                    b.Property<string>("SMTPPassword")
                        .HasMaxLength(50);

                    b.Property<int>("SMTPPort");

                    b.Property<string>("SMTPServer")
                        .HasMaxLength(50);

                    b.Property<string>("SMTPUsername")
                        .HasMaxLength(50);

                    b.Property<string>("SecurityCode")
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .HasMaxLength(150);

                    b.Property<int>("Status");

                    b.Property<string>("Street");

                    b.Property<DateTime>("UpdatedOnUtc");

                    b.Property<string>("Zip")
                        .HasMaxLength(50);

                    b.HasKey("BusinessId");

                    b.HasIndex("MarkupPlanId");

                    b.ToTable("BusinessEntities");
                });

            modelBuilder.Entity("Assignment.Web.Models.MarkupPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MarkupPlan");
                });

            modelBuilder.Entity("Assignment.Web.Models.BusinessEntities", b =>
                {
                    b.HasOne("Assignment.Web.Models.MarkupPlan", "MarkupPlan")
                        .WithMany("BusinessEntities")
                        .HasForeignKey("MarkupPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
